### ISSUE TITLE
Installable on the Tablet ?

### ISSUE THREAD

**Issue by gedw99** [skius/rm-pdf-tools#5]
This is a cool thing 

i had no idea a tablet like that exists .

just wondering if this golang code is able to be I stalled on the remarkable tablet ?

**Comment by skius** [comment]
Thanks for your interest. Frankly I don't know if this can be run on the reMarkable itself, but I wouldn't be surprised if a dependency (pdfcpu) caused issues. I also don't know if the reMarkable is even powerful enough to convert the PDFs in the manner I'm currently doing it now.

Just to be clear - the tool works by syncing with the cloud, which seems like a weird/wasteful approach when it is ran locally in the tablet (upload from reMarkable to the cloud, download from the cloud to the reMarkable, edit, upload from reMarkable to the cloud, download again to the reMarkable).

However, I have toyed with the idea of wrapping the tool on the device with something like https://github.com/ddvk/rmfakecloud so that hopefully it could be done offline, but none of this is implemented at the moment.

If you end up trying anything, please let me know how it goes!

**Comment by gedw99** [comment]
ah now i get it :) cloud sync

i personally think its nuts how they did not make open API's. insane to me.

I dont think i will do any work on this. Mostly because its so opaque and they can swap things under you.

going to close this..
